deploy:
  provider: heroku
  api_key:
    secure: zPT5jaEKkood/DO0UwJ1twKOlgFJdY6cApt5q0WEYuJ+PztZpMtxW1id8TGb6fyOlVI4V2RSYTvJC/ocXqNJ3gP3h+FSNuz8sykcYpzBBjLRwnHXwbkpVdl6iaEvyYVtSwIXaHs1HD7DenysQGKJUOSI+x9Idxvn7FnMn0OzbTzWbb1PJpxt56XQxu/U4/mBC0qWtGIHwkAW1UiWIJG3g/wuYwd3cMnMV71rluSc6py0rl3gfu7B00Ln142Iti6trKZQDJLz8M3kGimHQYmsnfMjuzcifRbPp40KPJAh1i0TzX7J+a7+T1ort97rD3hNg8bmJ4b6wPrhHzbY/Nxkun7I12REWFouLQ5nX1vhZ0fhXNQGimp2jBYOvonjeK3aDzWBvQH3Q53WCfL8THnYptRB0cyr40pEocZEpJpX+gxxF++Jd/i6o8HQEpfZ9D9/Ito2auQPPk/Bq/piMBuRQS28nXhwJS8EUIC32XsGGpIrjjwcKLKikU2SGnV1uMKcBwibsjjLe6JBzZ5YSqd7f/hFpQDVGAOBAR2emlpB153dLQnzkfMH2Q4qtM6Vxnlh98MG2EPoQHymEb2iZytmi4LkB3RN6ukznpO0/jUullHYrY2TJ0jklIiBlow4Wixapu6r7Yz2U/624eckR/jWJXtBQWgRs9cel80ea8Q2C6Y=
  app: intense-crag-68461
  on:
    repo: chrisongts/myproj
